services:
  abusara-app:
    image: beyond-gluten-frontend:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-beyond_gluten_front}
    ports:
      - "${APP_PORT:-3005}:3000" 
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge